### ISSUE TITLE
New-PureOneOperation - No access token found in the global variable or passed in.

### ISSUE THREAD

**Issue by ghostils** [PureStorage-OpenConnect/PureStorage.Pure1#25]
Following error after authentication and pulling arrays list:
`
New-PureOneConnection -certificate $certObject -pureAppID "blahblahblah"
$arrays = @()
$arrays = Get-PureOneArray
$arrays | select | where {$_.name -like "*MYTESTARRAY*"}

#-We get a values list of Arrays (id/hosts redacted):
id      : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
name    : MYTESTARRAY
fqdn    : MYTESTARRAY.FDQN
model   : FA-X20R2
os      : Purity//FA
version : 6.0.0
_as_of  : 1599061801000

#-/api/1.latest/alerts
$alerts = New-PureOneOperation -resourceType "alerts" -queryFilter "?names='MYTESTARRAY'" -restOperationType GET
`
`
No access token found in the global variable or passed in. Run the cmdlet New-PureOneRestConnection to authenticate.
At C:\Program Files\WindowsPowerShell\Modules\purestorage.pure1\PureStorage.Pure1.psm1:2078 char:9
+         throw "No access token found in the global variable or passed ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (No access token...o authenticate.:String) [], RuntimeException
    + FullyQualifiedErrorId : No access token found in the global variable or passed in. Run the cmdlet New-PureOneRestConnection to authenticate.
`
----------------------------------------------------------------------------------------------------------------------

$Global:DefaultPureOneConnection does not appear to be set as manually setting it to the active $Global:PureOneConnections

Does appear to carry on, but does not retrieve resources.

**Comment by codyhosterman** [comment]
Ah I see the issue. I made a last change in the module to remove the $DefaultPureOneConnections to instead make the $PureOneConnections have all of them and they have a property which indicates which is default. There are three places that still reference that variable. Will fix this quickly in a dot release.

**Comment by codyhosterman** [comment]
Okay fixed this. Simple fix in an internal function for setting the REST header. It was referencing the old variable--verified there are no other occurrences of this.

![image](https://user-images.githubusercontent.com/9014543/92023104-1faed580-ed11-11ea-8b32-e8badd8c82bd.png)

Improved my test plan to make sure to test this cmdlet without passing in a token, which is what most cmdlets leverage when calling it, which is why it was missed.

**Comment by codyhosterman** [comment]
I tested the alerts cmdlet that you used though and I think there is something wrong with that REST API--it doesnt seem to be an issue with the cmdlet. Can you run update-module PureStorage.Pure1 and let me know if at least it fixes that error for you? 

Also fixed an outstanding issue with Invoke-RestMethod not causing the cmdlet to terminate upon failure REST response (it throws non-terminating errors).

**Comment by codyhosterman** [comment]
By the way, I am not able to query by array name with names='array name' but like I said it does not seem to be an issue with the module, but the REST API itself. The following works through:

`$alerts = New-PureOneOperation -resourceType "alerts"  -restOperationType GET -QueryFilter "?filter=arrays.name='flasharray-m50-1'"`

**Comment by codyhosterman** [comment]
I am going to close this issue--let me know if the update does not fix the issue and I can re-open.

**Comment by ghostils** [comment]
Just tested 1.2.0.3 - confirming issue above resolved.  Also thank you for the pointer in the filter options I can pull open alerts now for all arrays!

**Comment by codyhosterman** [comment]
Awesome! Glad to hear! I think I will work on adding Get-PureOneAlert in the next release.
