### ISSUE TITLE
Get-PureOneVolume not returning all volumes on some arrays

### ISSUE THREAD

**Issue by Mutton4Life** [PureStorage-OpenConnect/PureStorage.Pure1#55]
I have an issue where all volumes on an array are not being reported by Get-PureOneVolume.  It seems that volumes migrated to new arrays using ActiveCluster are not being reported by Get-PureOneVolume.  The volumes do show up on the array and through the pure1 GUI.  The migrated volumes keep the serial number assigned to them on the original array, maybe this could be part of the issue?  

Get-PureOneVolume -ArrayName $FlashArray | Measure-Object | select count
Count
-----
   22

Get-Pfa2Volume -Array $FlashArray | Where-Object -Property serial -Like AXXXXXXXXXX* | Measure-Object | select count
Count
-----
   22

Get-Pfa2Volume -Array $FlashArray | Where-Object -Property serial -Like EXXXXXXXXXX* | Measure-Object | select count
Count
-----
   72

**Comment by codyhosterman** [comment]
Looked into this. This seems to be a Pure1 REST API issue, not the PowerShell module.

For instance, I have this volume in a pod:

![image](https://github.com/PureStorage-OpenConnect/PureStorage.Pure1/assets/9014543/1199ad2b-b157-4b01-bc24-7e9a847f2fb0)

And when I try to just flat out pull that volume from the REST, via PowerShell it is not there:

![image](https://github.com/PureStorage-OpenConnect/PureStorage.Pure1/assets/9014543/9b018a5f-9e56-49f1-bcec-075f9d3dd89b)

If I do it with a volume in a pod that did some from the array:
![image](https://github.com/PureStorage-OpenConnect/PureStorage.Pure1/assets/9014543/84f54a69-0300-4b0f-be97-1d8861431e30)

The PowerShell works (the API returns it)

![image](https://github.com/PureStorage-OpenConnect/PureStorage.Pure1/assets/9014543/dc321d28-97ad-4594-8854-b49b2cca7e8c)

So in the end this is a bug that Pure1 REST team needs to fix--nothing I can do with the module. I will keep this open though until it is resolved. Let me know if you disagree with this analysis

**Comment by codyhosterman** [comment]
@Mutton4Life according to the Pure1 folks the fix should be applied to the API and should be resolved. Please check and let me know and I will close this

**Comment by Mutton4Life** [comment]
Hey @codyhosterman I just verified that it is now working correctly!  Pure1 is returning the same number of volumes that I see on the arrays.  Thanks!
